import AudioFragment from './AudioFragment.vue'
import Character from './Character.vue'
import TTS from './TTS.vue'
import ASR from './ASR.vue'
import TipBtn from './TipBtn.vue'
import StudioToolbar from './StudioToolbar.vue'
import ToolbarButton from './ToolbarButton.vue'
import SpeakerSelectList from './SpeakerSelectList.vue'
import TxtEdit from './TxtEditor.vue'
import AudioEditor from './AudioEditor.vue'
import FragmentTrash from './FragmentTrash.vue'
import CreateBlankFragment from './CreateBlankFragment.vue'
import AudioUploader from './AudioUploader.vue'
export { AudioFragment, Character, TTS, ASR, TipBtn, StudioToolbar, ToolbarButton, SpeakerSelectList, TxtEdit, FragmentTrash, CreateBlankFragment, AudioEditor, AudioUploader }
